### PR TITLE
All templates: task apply-torizon-packages as dependency of build-container-torizon-* and build-image-sdk-*

### PR DESCRIPTION
**Pull request by griloHBG**
Before, `apply-torizon-packages` was dependency of `run-*` and `deploy-*` tasks. This way, one needed to run or deploy the application to update the related Dockerfiles with the last modification done on `torizonPackages.json`.

With this modification, the build process of the containers will depend on the `apply-torizon-packages`, therefore it will take into account modifications done on `torizonPackages.json` without the need to run or deploy the application.

### CODE REVIEW

**Comment by microhobby** [comment]
LGTM

@andreriesco could you also check?

**Review by microhobby — APPROVED** [review]

**Comment by andreriesco** [comment]
I just that the apply torizon packages step on the Dockerfiles of the Rust console and rust slint templates are missing.

 @microhobby, do you know if there is a reason for the Rust templates not to have them?

```
# your regular RUN statements here
# Install required packages
RUN apt-get -q -y update && \
    apt-get -q -y install \
# DO NOT REMOVE THIS LABEL: this is used for VS Code automation
    # __torizon_packages_prod_start__
    # __torizon_packages_prod_end__
# DO NOT REMOVE THIS LABEL: this is used for VS Code automation
    && apt-get clean && apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*
    ```

**Comment by microhobby** [comment]
> I just that the apply torizon packages step on the Dockerfiles of the Rust console and rust slint templates are missing.

@andreriesco please open an issue about this, since this is not related to the scope of this MR.

**Comment by andreriesco** [comment]
Sure, I just realized it was already there, at #121

**Comment by andreriesco** [comment]
LGTM

**Pull request merged**
