### PR TITLE
Draft: Release 2.6 Preparation

### PR DESCRIPTION
**Pull request by andreriesco**
Signed-off-by: Andre Riesco <andre.riesco@toradex.com>

### CODE REVIEW

**Comment by tronical** [comment]
I'd be super grateful if you could consider including https://github.com/commontorizon/Containerfiles/pull/14 and https://github.com/toradex/vscode-torizon-templates/pull/216 in this release.

We're also brewing a 1.7.2 release next week that includes a fix for the Toradex i.mx95 board.

**Comment by andreriesco** [comment]
Sure @tronical, I will add it and run the tests on it, thanks for point out.

**Comment by microhobby** [comment]
Hey @andreriesco I also cherry-picked the commits here for the https://github.com/toradex/vscode-torizon-templates/tree/next

**Comment by microhobby** [comment]
Hey @andreriesco maybe would be better if you get the `next` branch as base for your work. I cherry-picked your work there and had so solve a lot of conflicts already.

**Comment by microhobby** [comment]
Hey @andreriesco I added on `next` the follow changes:

dc02e32fa33d89ffd10eb6385cd3ba5be276db80
5bbfa9eb0d38423b286994a3417e3c9dafa3896d
29bba3bd011fdf848558124ef8d22d0a69a88be9

The reason is that this breaks the UX for the end of the tasks, as the reuse message is not shown, and appears that the tasks are still running when they are already finished.

**Comment by microhobby** [comment]
Hey @andreriesco , another change:

014506e1ea307c06df9c16297e8dcae769473af8

The reason is that red brings the idea of error or that the tasks crashed.

**Comment by andreriesco** [comment]
Closing this as it was merged into next

**Pull request closed without merging**
